### ISSUE TITLE
Object assign in IE

### ISSUE THREAD

**Issue by dardub** [KyleAMathews/react-responsive-grid#13]
In Container.cjsx, even though object-assign polyfill is used in a couple places, the coffeescript jsx compiler does not use it for spread operator. https://github.com/jsdf/coffee-react-transform/pull/71#event-625343301

So the compiled code results in

``` js
  return React.createElement("div", Object.assign({}, this.props, {
      "style": styles
    }), this.props.children, React.createElement("span", {
      "style": {
        display: 'block',
        clear: 'both'
      }
    }, ' '));
```

And we're getting Object assign errors in IE11.

As a related side note, we're using this in gatsby and I thought by default it includes the plugin babel-plugin-transform-object-assign, but I can't tell if that's working or not.

**Comment by KyleAMathews** [comment]
Yeah, either you have to add a polyfill (this module doesn't for you) or use babel-plugin-transform-object-assign. Gatsby has it available to use but it respects your .babelrc so if you don't have the plugin listed in your .babelrc the babel plugin won't be listed.

**Comment by NMinhNguyen** [comment]
@KyleAMathews Just hit this issue myself. My Gatsby project doesn't have an explicit `.babelrc` file, so I'm guessing it must be using the default one? Just to make sure I understood you correctly - do I simply need to create a `.babelrc` file (because I don't have one) with `babel-plugin-transform-object-assign` for this to work?
